DROP TABLE YoutubeData;
DROP TABLE IMDBData;

CREATE TABLE YoutubeData(
	Title VARCHAR (100) NOT NULL,
	Date TIMESTAMP NOT NULL,
	Description TEXT NOT NULL,
	Thumbnail VARCHAR (50) NOT NULL,
	URL VARCHAR (50) NOT NULL
);
	
CREATE TABLE IMDBData(
	Title VARCHAR (100) NOT NULL,
	Date TEXT NOT NULL
);